# first we pull the node image
FROM node:20

# environment variable to dl all the dev tools node need
ENV NODE_ENV=production
ENV PUBLIC_BASE_URL=http://localhost:3000
# Create a non-root user and group

WORKDIR /app

RUN apt-get update && apt-get install -y vim
RUN npm install -g pnpm

COPY ./build /app/build

COPY package-lock.json* ./
COPY package.json ./
RUN pnpm install --prod=true


EXPOSE 3000
CMD ["node", "build"]