services:
  nginx:
    image: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - miranda-prod
    networks:
      - miranda-network
    volumes:
      - /etc/letsencrypt/live/slahlou.tech:/etc/letsencrypt/live/slahlou.tech:ro
      - /etc/letsencrypt/archive/slahlou.tech:/etc/letsencrypt/archive/slahlou.tech:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
      - /etc/letsencrypt/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro
  miranda-prod:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: miranda-container-prod
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - miranda-network
networks:
  miranda-network:
    driver: bridge
