services:
  nginx:
    image: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.nginx
    ports:
      - '8080:8080'
    depends_on:
      - miranda-prod
    networks:
      - miranda-network
  miranda-prod:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: miranda-container-prod
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - miranda-network
networks:
  miranda-network:
    driver: bridge